"""SaaS product store protocol."""

from __future__ import annotations

from typing import Protocol

from saas_product.models import (
    BillingEventRecord,
    DeletionJob,
    InvitationRecord,
    InvoiceRecord,
    MembershipRecord,
    PrivacyExportJob,
    ProductAuditEvent,
    SubscriptionRecord,
    TenantRecord,
    UsageMeterRecord,
    UserAccount,
)


class SaaSProductStore(Protocol):
    def create_user(self, user: UserAccount) -> UserAccount: ...
    def get_user(self, user_id: str) -> UserAccount | None: ...
    def create_tenant(self, tenant: TenantRecord) -> TenantRecord: ...
    def get_tenant(self, tenant_id: str) -> TenantRecord | None: ...
    def list_tenants_for_user(self, user_id: str) -> tuple[TenantRecord, ...]: ...
    def create_membership(self, membership: MembershipRecord) -> MembershipRecord: ...
    def get_membership(self, membership_id: str) -> MembershipRecord | None: ...
    def get_active_membership(self, user_id: str, tenant_id: str) -> MembershipRecord | None: ...
    def list_memberships(self, tenant_id: str, *, limit: int = 50, offset: int = 0) -> tuple[list[MembershipRecord], int]: ...
    def update_membership(self, membership: MembershipRecord) -> MembershipRecord: ...
    def create_invitation(self, invitation: InvitationRecord) -> InvitationRecord: ...
    def get_invitation(self, invitation_id: str) -> InvitationRecord | None: ...
    def get_invitation_by_token_hash(self, token_hash: str) -> InvitationRecord | None: ...
    def list_invitations(self, tenant_id: str, *, status: str | None = None, limit: int = 50, offset: int = 0) -> tuple[list[InvitationRecord], int]: ...
    def update_invitation(self, invitation: InvitationRecord) -> InvitationRecord: ...
    def save_subscription(self, subscription: SubscriptionRecord) -> SubscriptionRecord: ...
    def get_subscription(self, subscription_id: str) -> SubscriptionRecord | None: ...
    def get_subscription_for_tenant(self, tenant_id: str) -> SubscriptionRecord | None: ...
    def save_invoice(self, invoice: InvoiceRecord) -> InvoiceRecord: ...
    def list_invoices(self, tenant_id: str, *, limit: int = 50, offset: int = 0) -> tuple[list[InvoiceRecord], int]: ...
    def record_billing_event(self, event: BillingEventRecord) -> BillingEventRecord: ...
    def get_billing_event(self, event_id: str) -> BillingEventRecord | None: ...
    def record_usage_meter(self, record: UsageMeterRecord) -> UsageMeterRecord: ...
    def sum_usage_meter(self, tenant_id: str, meter_id: str, period_key: str) -> int: ...
    def create_privacy_export(self, job: PrivacyExportJob) -> PrivacyExportJob: ...
    def get_privacy_export(self, job_id: str) -> PrivacyExportJob | None: ...
    def update_privacy_export(self, job: PrivacyExportJob) -> PrivacyExportJob: ...
    def list_privacy_exports(self, tenant_id: str, user_id: str, *, limit: int = 50, offset: int = 0) -> tuple[list[PrivacyExportJob], int]: ...
    def create_deletion_job(self, job: DeletionJob) -> DeletionJob: ...
    def get_deletion_job(self, job_id: str) -> DeletionJob | None: ...
    def update_deletion_job(self, job: DeletionJob) -> DeletionJob: ...
    def append_audit(self, event: ProductAuditEvent) -> ProductAuditEvent: ...
    def list_audit(self, tenant_id: str | None, *, limit: int = 50, offset: int = 0) -> tuple[list[ProductAuditEvent], int]: ...
    def count_active_owners(self, tenant_id: str) -> int: ...
    def close(self) -> None: ...
