"""Canonical document error codes — fail closed, no stack traces to callers."""

from __future__ import annotations


class DocumentError(RuntimeError):
    def __init__(self, reason: str):
        self.reason = reason
        self.error_code = reason
        super().__init__(reason)


UNSUPPORTED_DOCUMENT_TYPE = "unsupported_document_type"
UNSUPPORTED = UNSUPPORTED_DOCUMENT_TYPE
DOCUMENT_TYPE_MISMATCH = "document_type_mismatch"
DOCUMENT_TOO_LARGE = "document_too_large"
DOCUMENT_TOO_MANY_PAGES = "document_too_many_pages"
DOCUMENT_TOO_MANY_SHEETS = "document_too_many_sheets"
DOCUMENT_TOO_MANY_CELLS = "document_too_many_cells"
DOCUMENT_TOO_MANY_CHUNKS = "document_too_many_chunks"
DOCUMENT_PARSE_FAILED = "document_parse_failed"
DOCUMENT_REQUIRES_OCR = "document_requires_ocr"
OCR_REQUIRED = "ocr_required"
DOCUMENT_ENCRYPTED = "encrypted_document"
DOCUMENT_MALFORMED = "malformed_document"
INVALID_DOCUMENT = "invalid_document"
DOCUMENT_CORRUPT = "document_corrupt"
OCR_UNAVAILABLE = "ocr_unavailable"
OCR_FAILED = "ocr_failed"
PROVIDER_UNAVAILABLE = "provider_unavailable"
PDF_RASTERIZATION_UNAVAILABLE = "pdf_rasterization_unavailable"
LARGE_DOCUMENT_WORKFLOW_UNAVAILABLE = "large_document_workflow_unavailable"
STRUCTURED_EXTRACTION_FAILED = "structured_extraction_failed"
EXTRACTION_FAILED = "extraction_failed"
VALIDATION_FAILED = "validation_failed"
SCHEMA_VALIDATION_FAILED = "schema_validation_failed"
COMPARISON_FAILED = "comparison_failed"
RECONCILIATION_FAILED = "reconciliation_failed"
INSUFFICIENT_DATA = "insufficient_data"
GENERATION_FAILED = "generation_failed"
GENERATED_DOCUMENT_INVALID = "generated_document_invalid"
CONVERSION_UNAVAILABLE = "conversion_unavailable"
CONVERSION_FAILED = "conversion_failed"
DOCUMENT_MACROS_NOT_ALLOWED = "document_macros_not_allowed"
ARCHIVE_EXPANSION_LIMIT_EXCEEDED = "archive_expansion_limit_exceeded"
DOCUMENT_ACCESS_DENIED = "document_access_denied"
DOCUMENT_ENCRYPTION_UNAVAILABLE = "document_encryption_unavailable"
DOCUMENT_STORE_UNAVAILABLE = "document_store_unavailable"
DOCUMENT_RANGE_INVALID = "document_range_invalid"
DOCUMENT_SHEET_NOT_FOUND = "document_sheet_not_found"
DOCUMENT_PATH_DENIED = "document_path_denied"
DOCUMENT_SECRET_DENIED = "document_secret_denied"
DOCUMENT_DISABLED = "document_disabled"
ARTIFACT_NOT_FOUND = "artifact_not_found"
ARTIFACT_CORRUPT = "artifact_corrupt"
ARTIFACT_ACCESS_DENIED = "artifact_access_denied"
ARTIFACT_TOO_LARGE = "artifact_too_large"
TENANT_REQUIRED = "tenant_required"
NATIVE_EXTRACTION_FAILED = "native_extraction_failed"
CLASSIFICATION_FAILED = "classification_failed"
CLASSIFICATION_UNKNOWN = "classification_unknown"
DEADLINE_EXCEEDED = "deadline_exceeded"
CANCELLED = "cancelled"
CAPACITY_REJECTED = "capacity_rejected"
HARD_BATCH_ADMISSION_FAILED = "hard_batch_admission_failed"
DOCUMENT_OCR_BATCH_REQUIRED = "document_ocr_batch_required"
