"""Canonical file source categories for Files & Document Intelligence."""

from __future__ import annotations

from documents.models import (
    SOURCE_ACQUIRED,
    SOURCE_EXTERNAL_REFERENCE,
    SOURCE_GENERATED,
    SOURCE_INTERNAL_DATASET,
    SOURCE_SYSTEM,
    SOURCE_USER_UPLOAD,
    SOURCE_WORKFLOW,
)

# Platform-facing source category tokens (§6)
FILE_SOURCE_USER_UPLOAD = "USER_UPLOAD"
FILE_SOURCE_WORKFLOW_ARTIFACT = "WORKFLOW_ARTIFACT"
FILE_SOURCE_ACQUIRED_DOCUMENT = "ACQUIRED_DOCUMENT"
FILE_SOURCE_GENERATED_DOCUMENT = "GENERATED_DOCUMENT"
FILE_SOURCE_INTERNAL_DATASET = "INTERNAL_DATASET"
FILE_SOURCE_EXTERNAL_REFERENCE = "EXTERNAL_REFERENCE"

FILE_SOURCE_CATEGORIES = (
    FILE_SOURCE_USER_UPLOAD,
    FILE_SOURCE_WORKFLOW_ARTIFACT,
    FILE_SOURCE_ACQUIRED_DOCUMENT,
    FILE_SOURCE_GENERATED_DOCUMENT,
    FILE_SOURCE_INTERNAL_DATASET,
    FILE_SOURCE_EXTERNAL_REFERENCE,
)

_CATEGORY_TO_RECORD_SOURCE: dict[str, str] = {
    FILE_SOURCE_USER_UPLOAD: SOURCE_USER_UPLOAD,
    FILE_SOURCE_WORKFLOW_ARTIFACT: SOURCE_WORKFLOW,
    FILE_SOURCE_ACQUIRED_DOCUMENT: SOURCE_ACQUIRED,
    FILE_SOURCE_GENERATED_DOCUMENT: SOURCE_GENERATED,
    FILE_SOURCE_INTERNAL_DATASET: SOURCE_INTERNAL_DATASET,
    FILE_SOURCE_EXTERNAL_REFERENCE: SOURCE_EXTERNAL_REFERENCE,
}


def resolve_source_type(category: str, *, default: str = SOURCE_SYSTEM) -> str:
    """Map canonical category token → persisted ``DocumentRecord.source_type``."""
    if category in _CATEGORY_TO_RECORD_SOURCE:
        return _CATEGORY_TO_RECORD_SOURCE[category]
    if category in _CATEGORY_TO_RECORD_SOURCE.values():
        return category
    return default
