"""Operational activation status vocabulary for blocks 22–36."""

from __future__ import annotations

ENGINEERING_READY = "ENGINEERING_READY"
OFFLINE_VALIDATED = "OFFLINE_VALIDATED"
HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
LIVE_READ_VERIFIED = "LIVE_READ_VERIFIED"
LIVE_WRITE_VERIFIED = "LIVE_WRITE_VERIFIED"
METRICS_COLLECTING = "METRICS_COLLECTING"
METRICS_INSTRUMENTATION_READY = "METRICS_INSTRUMENTATION_READY"
REAL_PRODUCTION_SAMPLE_INSUFFICIENT = "REAL_PRODUCTION_SAMPLE_INSUFFICIENT"
WAITING_FOR_EVIDENCE = "WAITING_FOR_EVIDENCE"
PILOT_ACTIVE = "PILOT_ACTIVE"
CLOSED = "CLOSED"
OPEN = "OPEN"

# HITL WRITE lifecycle (governance) — real external WRITE remains zero until authorized
WRITE_PROPOSED = "PROPOSED"
WRITE_APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
WRITE_APPROVED = "APPROVED"
WRITE_EXECUTING = "EXECUTING"
WRITE_SUCCEEDED = "SUCCEEDED"
WRITE_FAILED = "FAILED"
WRITE_COMPENSATION_REQUIRED = "COMPENSATION_REQUIRED"

WRITE_STATES = frozenset(
    {
        WRITE_PROPOSED,
        WRITE_APPROVAL_REQUIRED,
        WRITE_APPROVED,
        WRITE_EXECUTING,
        WRITE_SUCCEEDED,
        WRITE_FAILED,
        WRITE_COMPENSATION_REQUIRED,
    }
)

ACTION_READ = "READ"
ACTION_SAFE_INTERNAL_WRITE = "SAFE_INTERNAL_WRITE"
ACTION_EXTERNAL_WRITE = "EXTERNAL_WRITE"
ACTION_HIGH_IMPACT_WRITE = "HIGH_IMPACT_WRITE"
