"""Commerce operations (17–19) fail-closed codes. Reuses publish access/live where identical."""

from __future__ import annotations

from governed_publish.errors import (
    PUBLISH_ACCESS_DENIED,
    PUBLISH_CAPABILITY_DENIED,
    PUBLISH_EMPTY_SELECTION,
    PUBLISH_LIVE_FORBIDDEN,
    PUBLISH_STALE,
    GovernedPublishError,
)

CommerceOpsError = GovernedPublishError

ACCESS_DENIED = PUBLISH_ACCESS_DENIED
CAPABILITY_DENIED = PUBLISH_CAPABILITY_DENIED
EMPTY_SELECTION = PUBLISH_EMPTY_SELECTION
LIVE_FORBIDDEN = PUBLISH_LIVE_FORBIDDEN
STALE_APPROVAL = PUBLISH_STALE

INVALID_PRICE = "INVALID_PRICE"
UNKNOWN_PRICE = "UNKNOWN_PRICE"
INCOMPLETE_ECONOMICS = "INCOMPLETE_ECONOMICS"
UNSAFE_PRICE = "UNSAFE_PRICE"
UNKNOWN_DISCOUNT_OWNERSHIP = "UNKNOWN_DISCOUNT_OWNERSHIP"
STALE_ECONOMICS = "STALE_ECONOMICS"
STALE_PRICE_SNAPSHOT = "STALE_PRICE_SNAPSHOT"
INVALID_STOCK = "INVALID_STOCK"
UNKNOWN_STOCK = "UNKNOWN_STOCK"
STALE_STOCK = "STALE_STOCK"
MISSING_MAPPING = "MISSING_MAPPING"
AMBIGUOUS_MAPPING = "AMBIGUOUS_MAPPING"
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
APPROVAL_REJECTED = "APPROVAL_REJECTED"
ALREADY_EXECUTED = "ALREADY_EXECUTED"
NOOP_PRICE = "NOOP_PRICE"
OVERRIDE_FORBIDDEN = "OVERRIDE_FORBIDDEN"
