"""Product Media Intelligence error taxonomy (Block 10)."""

from __future__ import annotations


class MediaError(RuntimeError):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.reason = code
        super().__init__(message or code)


MEDIA_INVALID = "MEDIA_INVALID"
MEDIA_UNSUPPORTED = "MEDIA_UNSUPPORTED"
MEDIA_TYPE_MISMATCH = "MEDIA_TYPE_MISMATCH"
MEDIA_CORRUPT = "MEDIA_CORRUPT"
MEDIA_TOO_LARGE = "MEDIA_TOO_LARGE"
MEDIA_PIXEL_LIMIT_EXCEEDED = "MEDIA_PIXEL_LIMIT_EXCEEDED"
MEDIA_BATCH_REQUIRED = "MEDIA_BATCH_REQUIRED"
MEDIA_ACCESS_DENIED = "MEDIA_ACCESS_DENIED"
MEDIA_CROSS_TENANT = "MEDIA_CROSS_TENANT"
MEDIA_NOT_FOUND = "MEDIA_NOT_FOUND"
MEDIA_VERSION_CONFLICT = "MEDIA_VERSION_CONFLICT"
MEDIA_PRODUCT_LINK_AMBIGUOUS = "MEDIA_PRODUCT_LINK_AMBIGUOUS"
MEDIA_QUALITY_FAILED = "MEDIA_QUALITY_FAILED"
MEDIA_SIMILARITY_FAILED = "MEDIA_SIMILARITY_FAILED"
MEDIA_TRANSFORM_INVALID = "MEDIA_TRANSFORM_INVALID"
MEDIA_TRANSFORM_FAILED = "MEDIA_TRANSFORM_FAILED"
MEDIA_PROVIDER_UNAVAILABLE = "MEDIA_PROVIDER_UNAVAILABLE"
MEDIA_GENERATION_FAILED = "MEDIA_GENERATION_FAILED"
MEDIA_EDIT_FAILED = "MEDIA_EDIT_FAILED"
MEDIA_OUTPUT_INVALID = "MEDIA_OUTPUT_INVALID"
MEDIA_VIDEO_UNSUPPORTED = "MEDIA_VIDEO_UNSUPPORTED"
MEDIA_VIDEO_TOO_LARGE = "MEDIA_VIDEO_TOO_LARGE"
MEDIA_CANCELLED = "MEDIA_CANCELLED"
MEDIA_DEADLINE_EXCEEDED = "MEDIA_DEADLINE_EXCEEDED"
MEDIA_DELETED = "MEDIA_DELETED"


class MediaBatchRequired(MediaError):
    def __init__(self):
        super().__init__(MEDIA_BATCH_REQUIRED)


class MediaPixelLimitExceeded(MediaError):
    def __init__(self):
        super().__init__(MEDIA_PIXEL_LIMIT_EXCEEDED)
