"""Block 12 SEO error taxonomy."""

from __future__ import annotations


class SeoMarketingError(RuntimeError):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.reason = code
        super().__init__(message or code)


SEO_TENANT_REQUIRED = "SEO_TENANT_REQUIRED"
SEO_ACCESS_DENIED = "SEO_ACCESS_DENIED"
SEO_SITE_NOT_FOUND = "SEO_SITE_NOT_FOUND"
SEO_PAGE_NOT_FOUND = "SEO_PAGE_NOT_FOUND"
SEO_INVALID_URL = "SEO_INVALID_URL"
SEO_SOURCE_DENIED = "SEO_SOURCE_DENIED"
SEO_BATCH_REQUIRED = "SEO_BATCH_REQUIRED"
SEO_KEYWORD_INVALID = "SEO_KEYWORD_INVALID"
SEO_PROPERTY_DENIED = "SEO_PROPERTY_DENIED"
SEO_ANALYTICS_PROPERTY_DENIED = "SEO_ANALYTICS_PROPERTY_DENIED"
SEO_PROVIDER_RATE_LIMITED = "SEO_PROVIDER_RATE_LIMITED"
SEO_PROVIDER_UNAVAILABLE = "SEO_PROVIDER_UNAVAILABLE"
SEO_PROVIDER_TIMEOUT = "SEO_PROVIDER_TIMEOUT"
SEO_STALE_RECOMMENDATION = "SEO_STALE_RECOMMENDATION"
SEO_APPROVAL_REQUIRED = "SEO_APPROVAL_REQUIRED"
SEO_VALIDATION_FAILED = "SEO_VALIDATION_FAILED"
SEO_CANCELLED = "SEO_CANCELLED"
SEO_CONFLICT = "SEO_CONFLICT"
SEO_INSUFFICIENT_DATA = "SEO_INSUFFICIENT_DATA"
SEO_METRIC_NOT_AVAILABLE = "SEO_METRIC_NOT_AVAILABLE"
SEO_CROSS_TENANT = "SEO_CROSS_TENANT"
SEO_RANK_UNAVAILABLE = "SEO_RANK_UNAVAILABLE"
SEO_SITEMAP_INVALID = "SEO_SITEMAP_INVALID"
SEO_ROBOTS_INVALID = "SEO_ROBOTS_INVALID"
SEO_BATCH_REQUIRED_ALIAS = SEO_BATCH_REQUIRED  # reuse
SEO_FACT_UNSUPPORTED = "SEO_FACT_UNSUPPORTED"
SEO_FEEDBACK_LOOP_BOUNDED = "SEO_FEEDBACK_LOOP_BOUNDED"


class SeoBatchRequired(SeoMarketingError):
    def __init__(self):
        super().__init__(SEO_BATCH_REQUIRED)
