"""Central SEO workload limits (Block 12)."""

from __future__ import annotations

MAX_SYNC_KEYWORDS = 25
MAX_SYNC_URLS = 20
MAX_SYNC_SC_ROWS = 50
MAX_SYNC_ANALYTICS_ROWS = 50
BULK_KEYWORD_BATCH_SIZE = 100
BULK_URL_BATCH_SIZE = 50
BULK_SC_PAGE_SIZE = 200
BULK_META_APPLY_BATCH_SIZE = 25
MIN_MEASUREMENT_WINDOW_DAYS = 7
MAX_REVISIONS_PER_WINDOW = 3
