"""SEO store ABC."""

from __future__ import annotations

from typing import Protocol

from seo_marketing.platform_models import (
    AnalyticsSnapshot,
    Keyword,
    MetaRecommendation,
    OptimizationDecision,
    OptimizationPlan,
    SearchConsoleSnapshot,
    SeoJob,
    SeoPage,
    SeoSite,
    TechnicalSeoAudit,
)


class SeoStore(Protocol):
    def save_site(self, site: SeoSite) -> None: ...
    def get_site(self, site_id: str, *, tenant_id: str) -> SeoSite | None: ...
    def save_page(self, page: SeoPage) -> None: ...
    def get_page(self, page_id: str, *, tenant_id: str) -> SeoPage | None: ...
    def list_pages(self, *, tenant_id: str, site_id: str) -> list[SeoPage]: ...
    def save_keyword(self, keyword: Keyword) -> None: ...
    def list_keywords(self, *, tenant_id: str, site_id: str) -> list[Keyword]: ...
    def save_recommendation(self, rec: MetaRecommendation) -> None: ...
    def get_recommendation(self, recommendation_id: str, *, tenant_id: str) -> MetaRecommendation | None: ...
    def save_sc_snapshot(self, snap: SearchConsoleSnapshot) -> None: ...
    def save_analytics_snapshot(self, snap: AnalyticsSnapshot) -> None: ...
    def save_technical_audit(self, audit: TechnicalSeoAudit) -> None: ...
    def save_plan(self, plan: OptimizationPlan) -> None: ...
    def get_plan(self, plan_id: str, *, tenant_id: str) -> OptimizationPlan | None: ...
    def save_decision(self, decision: OptimizationDecision) -> None: ...
    def save_job(self, job: SeoJob) -> None: ...
    def get_job(self, job_id: str, *, tenant_id: str) -> SeoJob | None: ...
