"""Block 20 order orchestration errors — reuse publish/ops codes where identical."""

from __future__ import annotations

from governed_publish.errors import (
    PUBLISH_ACCESS_DENIED,
    PUBLISH_CAPABILITY_DENIED,
    PUBLISH_LIVE_FORBIDDEN,
    PUBLISH_STALE,
    GovernedPublishError,
)

OrderOrchError = GovernedPublishError

ORDER_ACCESS_DENIED = PUBLISH_ACCESS_DENIED
CAPABILITY_DENIED = PUBLISH_CAPABILITY_DENIED
LIVE_FORBIDDEN = PUBLISH_LIVE_FORBIDDEN
STALE_APPROVAL = PUBLISH_STALE
APPROVAL_REJECTED = "APPROVAL_REJECTED"

INVALID_ORDER = "INVALID_ORDER"
UNSUPPORTED_SOURCE = "UNSUPPORTED_SOURCE"
MISSING_ORDER_ID = "MISSING_ORDER_ID"
INVALID_QUANTITY = "INVALID_QUANTITY"
INVALID_PRICE = "INVALID_PRICE"
CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
MISSING_PRODUCT_MAPPING = "MISSING_PRODUCT_MAPPING"
AMBIGUOUS_PRODUCT_MAPPING = "AMBIGUOUS_PRODUCT_MAPPING"
DUPLICATE_ORDER = "DUPLICATE_ORDER"
ORDER_CONFLICT = "ORDER_CONFLICT"
STALE_ORDER_EVENT = "STALE_ORDER_EVENT"
DOWNSTREAM_UNSUPPORTED = "DOWNSTREAM_UNSUPPORTED"
ONEC_BLOCKED = "ONEC_BLOCKED"
CRM_BLOCKED = "CRM_BLOCKED"
ALREADY_EXECUTED = "ALREADY_EXECUTED"
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
