"""Block 11 product platform error taxonomy."""

from __future__ import annotations


class ProductPlatformError(Exception):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        super().__init__(message or code)


COMMERCE_BATCH_REQUIRED = "COMMERCE_BATCH_REQUIRED"
COMMERCE_CROSS_TENANT = "COMMERCE_CROSS_TENANT"
COMMERCE_NOT_FOUND = "COMMERCE_NOT_FOUND"
COMMERCE_IDENTIFIER_CONFLICT = "COMMERCE_IDENTIFIER_CONFLICT"
COMMERCE_IMPORT_CONFLICT = "COMMERCE_IMPORT_CONFLICT"
COMMERCE_MATCH_AMBIGUOUS = "COMMERCE_MATCH_AMBIGUOUS"
COMMERCE_ENRICHMENT_CONFLICT = "COMMERCE_ENRICHMENT_CONFLICT"
COMMERCE_PRICE_DENIED = "COMMERCE_PRICE_DENIED"
COMMERCE_PRICE_STALE = "COMMERCE_PRICE_STALE"
COMMERCE_PRICE_INSUFFICIENT_DATA = "COMMERCE_PRICE_INSUFFICIENT_DATA"
COMMERCE_PRICE_STALE_DECISION = "COMMERCE_PRICE_STALE_DECISION"
COMMERCE_APPROVAL_REQUIRED = "COMMERCE_APPROVAL_REQUIRED"
COMMERCE_APPROVAL_REPLAY = "COMMERCE_APPROVAL_REPLAY"
COMMERCE_INSUFFICIENT_STOCK = "COMMERCE_INSUFFICIENT_STOCK"
COMMERCE_OVERSELL = "COMMERCE_OVERSELL"
COMMERCE_ORDER_INVALID = "COMMERCE_ORDER_INVALID"
COMMERCE_ORDER_TRANSITION_INVALID = "COMMERCE_ORDER_TRANSITION_INVALID"
COMMERCE_CMS_DENIED = "COMMERCE_CMS_DENIED"
COMMERCE_CMS_CONFLICT = "COMMERCE_CMS_CONFLICT"
COMMERCE_ACCESS_DENIED = "COMMERCE_ACCESS_DENIED"
COMMERCE_STOCK_STALE = "COMMERCE_STOCK_STALE"
COMMERCE_ORDER_STALE_EVENT = "COMMERCE_ORDER_STALE_EVENT"
COMMERCE_ORDER_EVENT_CONFLICT = "COMMERCE_ORDER_EVENT_CONFLICT"
COMMERCE_ORDER_EVENT_IDEMPOTENT = "COMMERCE_ORDER_EVENT_IDEMPOTENT"
COMMERCE_JOB_CANCELLED = "COMMERCE_JOB_CANCELLED"


class CommerceBatchRequired(ProductPlatformError):
    def __init__(self):
        super().__init__(COMMERCE_BATCH_REQUIRED)
