"""Central commerce workload limits (Block 11)."""

from __future__ import annotations

MAX_SYNC_IMPORT_ROWS = 50
MAX_SYNC_ENRICH_COUNT = 20
MAX_SYNC_REPRICE_COUNT = 10
MAX_SYNC_CMS_WRITES = 5
MAX_BULK_IMPORT_ROWS = 5000
BULK_APPLY_BATCH_SIZE = 10
BULK_CMS_SYNC_BATCH_SIZE = 5

IMPORT_PROFILE_VERSION = "1.0.0"
CATALOG_PROFILE_VERSION = "1.0.0"
PRICE_POLICY_VERSION = "1.0.0"
