"""Business / Digital Assistant error taxonomy."""

from __future__ import annotations


class BusinessAssistantError(Exception):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        super().__init__(message or code)


BA_INVALID_REQUEST = "BA_INVALID_REQUEST"
BA_PLAN_INVALID = "BA_PLAN_INVALID"
BA_PLAN_CYCLE = "BA_PLAN_CYCLE"
BA_CAPABILITY_UNAVAILABLE = "BA_CAPABILITY_UNAVAILABLE"
BA_CAPABILITY_FORBIDDEN = "BA_CAPABILITY_FORBIDDEN"
BA_APPROVAL_REQUIRED = "BA_APPROVAL_REQUIRED"
BA_APPROVAL_STALE = "BA_APPROVAL_STALE"
BA_APPROVAL_MISMATCH = "BA_APPROVAL_MISMATCH"
BA_CROSS_TENANT = "BA_CROSS_TENANT"
BA_ACCESS_DENIED = "BA_ACCESS_DENIED"
BA_READ_ONLY_WRITE_BLOCKED = "BA_READ_ONLY_WRITE_BLOCKED"
BA_LOOP_TERMINATED = "BA_LOOP_TERMINATED"
BA_STALE_PREVIEW = "BA_STALE_PREVIEW"
BA_CONNECTOR_NOT_CONFIGURED = "BA_CONNECTOR_NOT_CONFIGURED"
BA_BATCH_REQUIRED = "BA_BATCH_REQUIRED"
BA_NOT_FOUND = "BA_NOT_FOUND"
BA_CANCELLED = "BA_CANCELLED"
BA_FACT_UNSUPPORTED = "BA_FACT_UNSUPPORTED"
BA_AMBIGUOUS_MATCH = "BA_AMBIGUOUS_MATCH"
BA_INJECTION_BLOCKED = "BA_INJECTION_BLOCKED"
BA_BUDGET_EXCEEDED = "BA_BUDGET_EXCEEDED"
BA_CONVERSATION_UNAVAILABLE = "BA_CONVERSATION_UNAVAILABLE"
BA_DEADLINE_EXCEEDED = "BA_DEADLINE_EXCEEDED"
BA_STEP_FAILED = "BA_STEP_FAILED"
