"""Deterministic commerce / EDO / fiscal / marking state machines."""

from __future__ import annotations

from commerce.errors import InvalidTransitionError

# Order fulfillment states
ORDER_NEW = "NEW"
ORDER_VALIDATED = "VALIDATED"
ORDER_PAYMENT_PENDING = "PAYMENT_PENDING"
ORDER_PAID = "PAID"
ORDER_RESERVED = "RESERVED"
ORDER_FULFILLMENT = "FULFILLMENT"
ORDER_FISCALIZATION = "FISCALIZATION"
ORDER_MARKING = "MARKING"
ORDER_SHIPMENT = "SHIPMENT"
ORDER_COMPLETED = "COMPLETED"
ORDER_NEEDS_REVIEW = "NEEDS_REVIEW"
ORDER_COMPLIANCE_RISK = "COMPLIANCE_RISK"
ORDER_COMPLIANCE_PENDING = "COMPLIANCE_PENDING"
ORDER_RECONCILIATION_ERROR = "RECONCILIATION_ERROR"
ORDER_CANCEL_PENDING = "CANCEL_PENDING"
ORDER_RETURN_PENDING = "RETURN_PENDING"
ORDER_FAILED = "FAILED"
ORDER_CANCELLED = "CANCELLED"
ORDER_RETURNED = "RETURNED"

ORDER_STATES = frozenset(
    {
        ORDER_NEW,
        ORDER_VALIDATED,
        ORDER_PAYMENT_PENDING,
        ORDER_PAID,
        ORDER_RESERVED,
        ORDER_FULFILLMENT,
        ORDER_FISCALIZATION,
        ORDER_MARKING,
        ORDER_SHIPMENT,
        ORDER_COMPLETED,
        ORDER_NEEDS_REVIEW,
        ORDER_COMPLIANCE_RISK,
        ORDER_COMPLIANCE_PENDING,
        ORDER_RECONCILIATION_ERROR,
        ORDER_CANCEL_PENDING,
        ORDER_RETURN_PENDING,
        ORDER_FAILED,
        ORDER_CANCELLED,
        ORDER_RETURNED,
    }
)

_ORDER_TRANSITIONS: dict[str, frozenset[str]] = {
    ORDER_NEW: frozenset({ORDER_VALIDATED, ORDER_NEEDS_REVIEW, ORDER_FAILED, ORDER_CANCELLED}),
    ORDER_VALIDATED: frozenset(
        {ORDER_PAYMENT_PENDING, ORDER_PAID, ORDER_COMPLIANCE_RISK, ORDER_NEEDS_REVIEW, ORDER_CANCELLED}
    ),
    ORDER_PAYMENT_PENDING: frozenset({ORDER_PAID, ORDER_FAILED, ORDER_CANCELLED, ORDER_CANCEL_PENDING}),
    ORDER_PAID: frozenset(
        {ORDER_RESERVED, ORDER_NEEDS_REVIEW, ORDER_COMPLIANCE_RISK, ORDER_CANCEL_PENDING}
    ),
    ORDER_RESERVED: frozenset(
        {ORDER_FULFILLMENT, ORDER_CANCEL_PENDING, ORDER_NEEDS_REVIEW, ORDER_FAILED}
    ),
    ORDER_FULFILLMENT: frozenset(
        {
            ORDER_FISCALIZATION,
            ORDER_MARKING,
            ORDER_SHIPMENT,
            ORDER_COMPLIANCE_PENDING,
            ORDER_NEEDS_REVIEW,
            ORDER_CANCEL_PENDING,
        }
    ),
    ORDER_FISCALIZATION: frozenset(
        {ORDER_MARKING, ORDER_SHIPMENT, ORDER_COMPLIANCE_PENDING, ORDER_FAILED}
    ),
    ORDER_MARKING: frozenset(
        {ORDER_SHIPMENT, ORDER_COMPLIANCE_PENDING, ORDER_FAILED, ORDER_NEEDS_REVIEW}
    ),
    ORDER_SHIPMENT: frozenset(
        {ORDER_COMPLETED, ORDER_COMPLIANCE_PENDING, ORDER_RETURN_PENDING, ORDER_RECONCILIATION_ERROR}
    ),
    ORDER_COMPLIANCE_PENDING: frozenset(
        {ORDER_FULFILLMENT, ORDER_FISCALIZATION, ORDER_MARKING, ORDER_SHIPMENT, ORDER_FAILED, ORDER_NEEDS_REVIEW}
    ),
    ORDER_COMPLIANCE_RISK: frozenset({ORDER_VALIDATED, ORDER_PAID, ORDER_NEEDS_REVIEW, ORDER_FAILED, ORDER_CANCELLED}),
    ORDER_NEEDS_REVIEW: frozenset(
        {ORDER_VALIDATED, ORDER_PAID, ORDER_RESERVED, ORDER_FULFILLMENT, ORDER_FAILED, ORDER_CANCELLED}
    ),
    ORDER_CANCEL_PENDING: frozenset({ORDER_CANCELLED, ORDER_FAILED, ORDER_RETURN_PENDING}),
    ORDER_RETURN_PENDING: frozenset({ORDER_RETURNED, ORDER_FAILED, ORDER_RECONCILIATION_ERROR}),
    ORDER_RECONCILIATION_ERROR: frozenset({ORDER_NEEDS_REVIEW, ORDER_COMPLETED, ORDER_FAILED}),
    ORDER_FAILED: frozenset({ORDER_NEEDS_REVIEW, ORDER_CANCELLED}),
    ORDER_COMPLETED: frozenset({ORDER_RETURN_PENDING}),
    ORDER_CANCELLED: frozenset(),
    ORDER_RETURNED: frozenset(),
}

# EDO
EDO_DRAFT = "DRAFT"
EDO_PREPARED = "PREPARED"
EDO_SIGNED = "SIGNED"
EDO_SENT = "SENT"
EDO_DELIVERED = "DELIVERED"
EDO_ACCEPTED = "ACCEPTED"
EDO_REJECTED = "REJECTED"
EDO_CORRECTION_REQUIRED = "CORRECTION_REQUIRED"
EDO_CANCELLED = "CANCELLED"
EDO_ERROR = "ERROR"

_EDO_TRANSITIONS = {
    EDO_DRAFT: frozenset({EDO_PREPARED, EDO_CANCELLED, EDO_ERROR}),
    EDO_PREPARED: frozenset({EDO_SIGNED, EDO_CORRECTION_REQUIRED, EDO_CANCELLED, EDO_ERROR}),
    EDO_SIGNED: frozenset({EDO_SENT, EDO_ERROR}),
    EDO_SENT: frozenset({EDO_DELIVERED, EDO_REJECTED, EDO_ERROR}),
    EDO_DELIVERED: frozenset({EDO_ACCEPTED, EDO_REJECTED, EDO_CORRECTION_REQUIRED}),
    EDO_CORRECTION_REQUIRED: frozenset({EDO_PREPARED, EDO_CANCELLED}),
    EDO_REJECTED: frozenset({EDO_CORRECTION_REQUIRED, EDO_CANCELLED}),
    EDO_ACCEPTED: frozenset(),
    EDO_CANCELLED: frozenset(),
    EDO_ERROR: frozenset({EDO_DRAFT, EDO_CANCELLED}),
}

# Fiscal
FISCAL_PENDING = "PENDING"
FISCAL_SUBMITTED = "SUBMITTED"
FISCAL_FISCALIZED = "FISCALIZED"
FISCAL_OFD_CONFIRMED = "OFD_CONFIRMED"
FISCAL_FAILED = "FAILED"
FISCAL_CORRECTION_REQUIRED = "CORRECTION_REQUIRED"
FISCAL_REFUND_PENDING = "REFUND_PENDING"
FISCAL_REFUNDED = "REFUNDED"

_FISCAL_TRANSITIONS = {
    FISCAL_PENDING: frozenset({FISCAL_SUBMITTED, FISCAL_FAILED}),
    FISCAL_SUBMITTED: frozenset({FISCAL_FISCALIZED, FISCAL_FAILED, FISCAL_CORRECTION_REQUIRED}),
    FISCAL_FISCALIZED: frozenset({FISCAL_OFD_CONFIRMED, FISCAL_REFUND_PENDING, FISCAL_FAILED}),
    FISCAL_OFD_CONFIRMED: frozenset({FISCAL_REFUND_PENDING}),
    FISCAL_CORRECTION_REQUIRED: frozenset({FISCAL_SUBMITTED, FISCAL_FAILED}),
    FISCAL_REFUND_PENDING: frozenset({FISCAL_REFUNDED, FISCAL_FAILED}),
    FISCAL_FAILED: frozenset({FISCAL_PENDING, FISCAL_CORRECTION_REQUIRED}),
    FISCAL_REFUNDED: frozenset(),
}

# Marking code orchestration states
MARKING_AVAILABLE = "AVAILABLE"
MARKING_RESERVED = "RESERVED"
MARKING_TRANSFERRED = "TRANSFERRED"
MARKING_WITHDRAWN = "WITHDRAWN"
MARKING_RETURNED = "RETURNED"
MARKING_REINTRODUCED = "REINTRODUCED"
MARKING_ERROR = "ERROR"

_MARKING_TRANSITIONS = {
    MARKING_AVAILABLE: frozenset({MARKING_RESERVED, MARKING_TRANSFERRED, MARKING_WITHDRAWN, MARKING_ERROR}),
    MARKING_RESERVED: frozenset({MARKING_TRANSFERRED, MARKING_WITHDRAWN, MARKING_AVAILABLE, MARKING_ERROR}),
    MARKING_TRANSFERRED: frozenset({MARKING_RETURNED, MARKING_ERROR}),
    MARKING_WITHDRAWN: frozenset({MARKING_REINTRODUCED, MARKING_ERROR}),
    MARKING_RETURNED: frozenset({MARKING_AVAILABLE, MARKING_REINTRODUCED}),
    MARKING_REINTRODUCED: frozenset({MARKING_AVAILABLE}),
    MARKING_ERROR: frozenset({MARKING_AVAILABLE}),
}


def assert_transition(machine: str, current: str, target: str) -> None:
    tables = {
        "order": _ORDER_TRANSITIONS,
        "edo": _EDO_TRANSITIONS,
        "fiscal": _FISCAL_TRANSITIONS,
        "marking": _MARKING_TRANSITIONS,
    }
    table = tables.get(machine)
    if table is None:
        raise InvalidTransitionError("invalid_transition")
    allowed = table.get(current, frozenset())
    if target not in allowed:
        raise InvalidTransitionError("invalid_transition")


def can_transition(machine: str, current: str, target: str) -> bool:
    try:
        assert_transition(machine, current, target)
        return True
    except InvalidTransitionError:
        return False
