"""Business Assistant API error taxonomy."""

from __future__ import annotations


class BusinessAssistantApiError(Exception):
    def __init__(self, code: str, message: str = "", *, http_status: int = 400):
        self.code = code
        self.message = message or code
        self.http_status = http_status
        super().__init__(self.message)


BAA_INVALID_REQUEST = "BAA_INVALID_REQUEST"
BAA_AUTH_FAILED = "BAA_AUTH_FAILED"
BAA_ACCESS_DENIED = "BAA_ACCESS_DENIED"
BAA_TENANT_MISMATCH = "BAA_TENANT_MISMATCH"
BAA_NOT_FOUND = "BAA_NOT_FOUND"
BAA_UNSUPPORTED_CAPABILITY = "BAA_UNSUPPORTED_CAPABILITY"
BAA_INVALID_STATE = "BAA_INVALID_STATE"
BAA_APPROVAL_REQUIRED = "BAA_APPROVAL_REQUIRED"
BAA_APPROVAL_STALE = "BAA_APPROVAL_STALE"
BAA_REJECTED = "BAA_REJECTED"
BAA_CANCELLED = "BAA_CANCELLED"
BAA_IDEMPOTENCY_CONFLICT = "BAA_IDEMPOTENCY_CONFLICT"
BAA_PROVIDER_UNAVAILABLE = "BAA_PROVIDER_UNAVAILABLE"
BAA_INTEGRATION_UNAVAILABLE = "BAA_INTEGRATION_UNAVAILABLE"
BAA_RATE_LIMITED = "BAA_RATE_LIMITED"
BAA_BUDGET_BLOCKED = "BAA_BUDGET_BLOCKED"
BAA_TIMEOUT = "BAA_TIMEOUT"
BAA_CONVERSATION_UNAVAILABLE = "BAA_CONVERSATION_UNAVAILABLE"
BAA_WORKFLOW_FAILED = "BAA_WORKFLOW_FAILED"
BAA_INTERNAL = "BAA_INTERNAL"
