"""Marketplace Platform error taxonomy."""

from __future__ import annotations


class MarketplaceError(Exception):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        super().__init__(message or code)


MARKETPLACE_AUTH = "MARKETPLACE_AUTH"
MARKETPLACE_RATE_LIMIT = "MARKETPLACE_RATE_LIMIT"
MARKETPLACE_UNAVAILABLE = "MARKETPLACE_UNAVAILABLE"
MARKETPLACE_INVALID_CARD = "MARKETPLACE_INVALID_CARD"
MARKETPLACE_CATEGORY_INVALID = "MARKETPLACE_CATEGORY_INVALID"
MARKETPLACE_ATTRIBUTE_INVALID = "MARKETPLACE_ATTRIBUTE_INVALID"
MARKETPLACE_CAPABILITY_UNSUPPORTED = "MARKETPLACE_CAPABILITY_UNSUPPORTED"
MARKETPLACE_PRICE_REJECTED = "MARKETPLACE_PRICE_REJECTED"
MARKETPLACE_STOCK_REJECTED = "MARKETPLACE_STOCK_REJECTED"
MARKETPLACE_ORDER_CONFLICT = "MARKETPLACE_ORDER_CONFLICT"
MARKETPLACE_REVIEW_CONFLICT = "MARKETPLACE_REVIEW_CONFLICT"
MARKETPLACE_SYNC_CONFLICT = "MARKETPLACE_SYNC_CONFLICT"

MARKETPLACE_SELECTION_REQUIRED = "MARKETPLACE_SELECTION_REQUIRED"
MARKETPLACE_SELECTION_INVALID = "MARKETPLACE_SELECTION_INVALID"
MARKETPLACE_LISTING_CONFLICT = "MARKETPLACE_LISTING_CONFLICT"
MARKETPLACE_MAPPING_AMBIGUOUS = "MARKETPLACE_MAPPING_AMBIGUOUS"
MARKETPLACE_PRICE_FLOOR = "MARKETPLACE_PRICE_FLOOR"
MARKETPLACE_LOSS_DETECTED = "MARKETPLACE_LOSS_DETECTED"
MARKETPLACE_ECONOMICS_UNKNOWN = "MARKETPLACE_ECONOMICS_UNKNOWN"
MARKETPLACE_PROMOTION_RISK = "MARKETPLACE_PROMOTION_RISK"
MARKETPLACE_AUTO_CORRECT_DENIED = "MARKETPLACE_AUTO_CORRECT_DENIED"
MARKETPLACE_STOCK_STALE = "MARKETPLACE_STOCK_STALE"
MARKETPLACE_CROSS_TENANT = "MARKETPLACE_CROSS_TENANT"
MARKETPLACE_APPROVAL_REQUIRED = "MARKETPLACE_APPROVAL_REQUIRED"
MARKETPLACE_BATCH_REQUIRED = "MARKETPLACE_BATCH_REQUIRED"
MARKETPLACE_CANCELLED = "MARKETPLACE_CANCELLED"
MARKETPLACE_SYNC_LOOP_TERMINATED = "MARKETPLACE_SYNC_LOOP_TERMINATED"
MARKETPLACE_NOT_FOUND = "MARKETPLACE_NOT_FOUND"
MARKETPLACE_ACCESS_DENIED = "MARKETPLACE_ACCESS_DENIED"
