"""UI Chat store interface."""

from __future__ import annotations

from typing import Protocol

from ui_chat.models import (
    AttachmentRef,
    BackgroundTaskView,
    ChatConversation,
    ChatMessage,
    ChatRun,
    VoiceAudioArtifact,
    VoiceTranscript,
)


class UIChatStore(Protocol):
    @property
    def available(self) -> bool: ...

    def create_conversation(self, conv: ChatConversation) -> ChatConversation: ...
    def update_conversation(self, conv: ChatConversation) -> ChatConversation: ...
    def list_conversations(self, *, tenant_id: str, user_id: str, limit: int = 50) -> list[ChatConversation]: ...
    def get_conversation(self, conversation_id: str, *, tenant_id: str) -> ChatConversation | None: ...

    def add_message(self, msg: ChatMessage) -> ChatMessage: ...
    def list_messages(self, conversation_id: str, *, tenant_id: str, limit: int = 200) -> list[ChatMessage]: ...
    def get_message(self, message_id: str, *, tenant_id: str) -> ChatMessage | None: ...

    def save_attachment(self, ref: AttachmentRef) -> AttachmentRef: ...
    def get_attachment(self, attachment_id: str, *, tenant_id: str) -> AttachmentRef | None: ...
    def update_attachment(self, ref: AttachmentRef) -> AttachmentRef: ...

    def save_run(self, run: ChatRun) -> ChatRun: ...
    def get_run(self, run_id: str, *, tenant_id: str) -> ChatRun | None: ...
    def get_run_by_idempotency(
        self, *, tenant_id: str, conversation_id: str, idempotency_key: str
    ) -> ChatRun | None: ...
    def list_runs_for_conversation(self, conversation_id: str, *, tenant_id: str) -> list[ChatRun]: ...

    def save_transcript(self, t: VoiceTranscript) -> VoiceTranscript: ...
    def save_voice_artifact(self, a: VoiceAudioArtifact, *, blob: bytes) -> VoiceAudioArtifact: ...
    def get_voice_artifact(self, artifact_id: str, *, tenant_id: str) -> VoiceAudioArtifact | None: ...
    def get_voice_artifact_blob(self, artifact_id: str, *, tenant_id: str) -> bytes | None: ...
    def find_voice_artifact(
        self, *, tenant_id: str, message_id: str, message_version: int
    ) -> VoiceAudioArtifact | None: ...

    def save_task(self, task: BackgroundTaskView) -> BackgroundTaskView: ...
    def get_task(self, task_id: str, *, tenant_id: str) -> BackgroundTaskView | None: ...
    def list_tasks(self, *, tenant_id: str, user_id: str, limit: int = 50) -> list[BackgroundTaskView]: ...

    def close(self) -> None: ...
