"""Controlled automation errors."""

from __future__ import annotations


class ControlledAutomationError(Exception):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.message = message or code
        super().__init__(self.message)


FORBIDDEN = "FORBIDDEN"
TENANT_SCOPE_VIOLATION = "TENANT_SCOPE_VIOLATION"
AUTOMATION_NOT_FOUND = "AUTOMATION_NOT_FOUND"
INVALID_AUTOMATION = "INVALID_AUTOMATION"
STALE_VERSION = "STALE_VERSION"
POLICY_DENIED = "POLICY_DENIED"
ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED"
RISK_HITL_REQUIRED = "RISK_HITL_REQUIRED"
CAPABILITY_DENIED = "CAPABILITY_DENIED"
BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
CONDITION_UNKNOWN = "CONDITION_UNKNOWN"
CONDITION_STALE = "CONDITION_STALE"
CONDITION_PARTIAL = "CONDITION_PARTIAL"
OVERLAP_BLOCKED = "OVERLAP_BLOCKED"
RATE_LIMITED = "RATE_LIMITED"
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
APPROVAL_REJECTED = "APPROVAL_REJECTED"
APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
APPROVAL_STALE = "APPROVAL_STALE"
LOOP_PREVENTED = "LOOP_PREVENTED"
LIVE_FALLBACK_FORBIDDEN = "LIVE_FALLBACK_FORBIDDEN"
DRY_RUN_ONLY = "DRY_RUN_ONLY"
