"""Knowledge platform error taxonomy (Block 8)."""

from __future__ import annotations


class KnowledgeError(RuntimeError):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.reason = code
        super().__init__(message or code)


# Ingestion
KNOWLEDGE_SOURCE_INVALID = "KNOWLEDGE_SOURCE_INVALID"
KNOWLEDGE_SOURCE_UNSUPPORTED = "KNOWLEDGE_SOURCE_UNSUPPORTED"
KNOWLEDGE_ACCESS_DENIED = "KNOWLEDGE_ACCESS_DENIED"
KNOWLEDGE_CROSS_TENANT = "KNOWLEDGE_CROSS_TENANT"
KNOWLEDGE_TOO_LARGE = "KNOWLEDGE_TOO_LARGE"
KNOWLEDGE_BATCH_REQUIRED = "KNOWLEDGE_BATCH_REQUIRED"
KNOWLEDGE_INGEST_FAILED = "KNOWLEDGE_INGEST_FAILED"
KNOWLEDGE_INDEX_FAILED = "KNOWLEDGE_INDEX_FAILED"
KNOWLEDGE_INDEX_INCOMPATIBLE = "KNOWLEDGE_INDEX_INCOMPATIBLE"

# Retrieval
KNOWLEDGE_RETRIEVAL_FAILED = "KNOWLEDGE_RETRIEVAL_FAILED"
KNOWLEDGE_NO_RESULTS = "KNOWLEDGE_NO_RESULTS"
KNOWLEDGE_SCOPE_INVALID = "KNOWLEDGE_SCOPE_INVALID"
KNOWLEDGE_VERSION_CONFLICT = "KNOWLEDGE_VERSION_CONFLICT"

# Lifecycle
KNOWLEDGE_DELETE_DENIED = "KNOWLEDGE_DELETE_DENIED"
KNOWLEDGE_DELETE_FAILED = "KNOWLEDGE_DELETE_FAILED"
KNOWLEDGE_DELETED = "KNOWLEDGE_DELETED"
KNOWLEDGE_EXPIRED = "KNOWLEDGE_EXPIRED"
KNOWLEDGE_CANCELLED = "KNOWLEDGE_CANCELLED"
KNOWLEDGE_DEADLINE_EXCEEDED = "KNOWLEDGE_DEADLINE_EXCEEDED"


class KnowledgeBatchRequired(KnowledgeError):
    def __init__(self):
        super().__init__(KNOWLEDGE_BATCH_REQUIRED)


class KnowledgeIndexIncompatible(KnowledgeError):
    def __init__(self, detail: str = ""):
        super().__init__(KNOWLEDGE_INDEX_INCOMPATIBLE, detail)


class KnowledgeNoResults(KnowledgeError):
    def __init__(self):
        super().__init__(KNOWLEDGE_NO_RESULTS)
