"""Block 13 B2B error taxonomy."""

from __future__ import annotations


class B2BCommerceError(RuntimeError):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.reason = code
        super().__init__(message or code)


B2B_TENANT_REQUIRED = "B2B_TENANT_REQUIRED"
B2B_ACCESS_DENIED = "B2B_ACCESS_DENIED"
B2B_SUPPLIER_NOT_FOUND = "B2B_SUPPLIER_NOT_FOUND"
B2B_SUPPLIER_DISABLED = "B2B_SUPPLIER_DISABLED"
B2B_SOURCE_DENIED = "B2B_SOURCE_DENIED"
B2B_PRICE_LIST_INVALID = "B2B_PRICE_LIST_INVALID"
B2B_CURRENCY_UNKNOWN = "B2B_CURRENCY_UNKNOWN"
B2B_CURRENCY_MISMATCH = "B2B_CURRENCY_MISMATCH"
B2B_VAT_UNKNOWN = "B2B_VAT_UNKNOWN"
B2B_PRODUCT_UNMATCHED = "B2B_PRODUCT_UNMATCHED"
B2B_PRODUCT_AMBIGUOUS = "B2B_PRODUCT_AMBIGUOUS"
B2B_OFFER_STALE = "B2B_OFFER_STALE"
B2B_CUSTOMER_NOT_FOUND = "B2B_CUSTOMER_NOT_FOUND"
B2B_CUSTOMER_UNVERIFIED = "B2B_CUSTOMER_UNVERIFIED"
B2B_QUANTITY_REQUIRED = "B2B_QUANTITY_REQUIRED"
B2B_QUOTE_STALE = "B2B_QUOTE_STALE"
B2B_QUOTE_APPROVAL_REQUIRED = "B2B_QUOTE_APPROVAL_REQUIRED"
B2B_MARGIN_POLICY_DENIED = "B2B_MARGIN_POLICY_DENIED"
B2B_ORDER_CONFIRMATION_REQUIRED = "B2B_ORDER_CONFIRMATION_REQUIRED"
B2B_TELEGRAM_BINDING_DENIED = "B2B_TELEGRAM_BINDING_DENIED"
B2B_TELEGRAM_DUPLICATE_UPDATE = "B2B_TELEGRAM_DUPLICATE_UPDATE"
B2B_TELEGRAM_PROVIDER_FAILED = "B2B_TELEGRAM_PROVIDER_FAILED"
B2B_BATCH_REQUIRED = "B2B_BATCH_REQUIRED"
B2B_CANCELLED = "B2B_CANCELLED"
B2B_CONFLICT = "B2B_CONFLICT"
B2B_FX_UNAVAILABLE = "B2B_FX_UNAVAILABLE"
B2B_ACTION_DENIED = "B2B_ACTION_DENIED"


class B2BBatchRequired(B2BCommerceError):
    def __init__(self):
        super().__init__(B2B_BATCH_REQUIRED)
