"""B2B repository protocol."""

from __future__ import annotations

from typing import Protocol

from b2b_commerce.platform_models import (
    B2BConversation,
    B2BConversationMessage,
    B2BCustomer,
    B2BInquiry,
    B2BInquiryItem,
    B2BJob,
    B2BOrderDraft,
    CommercialQuoteVersion,
    Supplier,
    SupplierPriceListVersion,
    TelegramAccountBinding,
    TelegramChatBinding,
    TelegramMessageReceipt,
    WholesaleOfferVersion,
    WholesaleProductMatch,
)


class B2BStore(Protocol):
    def save_supplier(self, supplier: Supplier) -> None: ...
    def get_supplier(self, tenant_id: str, supplier_id: str) -> Supplier | None: ...
    def list_suppliers(self, tenant_id: str) -> list[Supplier]: ...

    def save_price_list_version(self, version: SupplierPriceListVersion) -> None: ...
    def get_price_list_version(self, tenant_id: str, version_id: str) -> SupplierPriceListVersion | None: ...
    def find_price_list_by_hash(self, tenant_id: str, supplier_id: str, artifact_hash: str) -> SupplierPriceListVersion | None: ...

    def save_offer(self, offer: WholesaleOfferVersion) -> None: ...
    def get_offer(self, tenant_id: str, offer_id: str, version_id: str) -> WholesaleOfferVersion | None: ...
    def list_offers(self, tenant_id: str, *, supplier_id: str = "") -> list[WholesaleOfferVersion]: ...
    def list_offer_versions(self, tenant_id: str, offer_id: str) -> list[WholesaleOfferVersion]: ...

    def save_match(self, match: WholesaleProductMatch) -> None: ...
    def get_match(self, tenant_id: str, match_id: str) -> WholesaleProductMatch | None: ...

    def save_customer(self, customer: B2BCustomer) -> None: ...
    def get_customer(self, tenant_id: str, customer_id: str) -> B2BCustomer | None: ...

    def save_telegram_account(self, binding: TelegramAccountBinding) -> None: ...
    def get_telegram_account_by_bot(self, tenant_id: str, bot_id: str) -> TelegramAccountBinding | None: ...
    def get_telegram_account(self, tenant_id: str, binding_id: str) -> TelegramAccountBinding | None: ...

    def save_telegram_chat(self, binding: TelegramChatBinding) -> None: ...
    def get_telegram_chat(self, tenant_id: str, chat_id: str, account_binding_id: str) -> TelegramChatBinding | None: ...

    def save_conversation(self, conversation: B2BConversation) -> None: ...
    def get_conversation(self, tenant_id: str, conversation_id: str) -> B2BConversation | None: ...

    def save_message(self, message: B2BConversationMessage) -> None: ...
    def list_messages(self, tenant_id: str, conversation_id: str) -> list[B2BConversationMessage]: ...

    def save_inquiry(self, inquiry: B2BInquiry) -> None: ...
    def get_inquiry(self, tenant_id: str, inquiry_id: str) -> B2BInquiry | None: ...
    def save_inquiry_item(self, item: B2BInquiryItem) -> None: ...
    def list_inquiry_items(self, tenant_id: str, inquiry_id: str) -> list[B2BInquiryItem]: ...

    def save_quote(self, quote: CommercialQuoteVersion) -> None: ...
    def get_quote(self, tenant_id: str, quote_id: str, version_id: str) -> CommercialQuoteVersion | None: ...
    def list_quote_versions(self, tenant_id: str, quote_id: str) -> list[CommercialQuoteVersion]: ...

    def save_order_draft(self, draft: B2BOrderDraft) -> None: ...
    def get_order_draft(self, tenant_id: str, draft_id: str) -> B2BOrderDraft | None: ...

    def save_job(self, job: B2BJob) -> None: ...
    def get_job(self, tenant_id: str, job_id: str) -> B2BJob | None: ...

    def save_receipt(self, receipt: TelegramMessageReceipt) -> None: ...
    def get_receipt_by_idempotency(self, tenant_id: str, idempotency_key: str) -> TelegramMessageReceipt | None: ...

    def has_telegram_update(self, tenant_id: str, update_id: str) -> bool: ...
    def mark_telegram_update(self, tenant_id: str, update_id: str) -> None: ...

    def save_confirmation(self, tenant_id: str, token: str, payload: dict) -> None: ...
    def get_confirmation(self, tenant_id: str, token: str) -> dict | None: ...
    def consume_confirmation(self, tenant_id: str, token: str) -> dict | None: ...
