"""Content Intelligence error taxonomy (Block 9)."""

from __future__ import annotations


class ContentIntelError(RuntimeError):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.reason = code
        super().__init__(message or code)


CONTENT_REQUEST_INVALID = "CONTENT_REQUEST_INVALID"
CONTENT_ACCESS_DENIED = "CONTENT_ACCESS_DENIED"
CONTENT_CROSS_TENANT = "CONTENT_CROSS_TENANT"
CONTENT_RESEARCH_FAILED = "CONTENT_RESEARCH_FAILED"
CONTENT_RESEARCH_INSUFFICIENT_EVIDENCE = "CONTENT_RESEARCH_INSUFFICIENT_EVIDENCE"
CONTENT_SOURCE_STALE = "CONTENT_SOURCE_STALE"
CONTENT_STRATEGY_INVALID = "CONTENT_STRATEGY_INVALID"
CONTENT_GENERATION_FAILED = "CONTENT_GENERATION_FAILED"
CONTENT_MODEL_OUTPUT_INVALID = "CONTENT_MODEL_OUTPUT_INVALID"
CONTENT_FACT_UNSUPPORTED = "CONTENT_FACT_UNSUPPORTED"
CONTENT_DUPLICATE = "CONTENT_DUPLICATE"
CONTENT_MEDIA_UNAVAILABLE = "CONTENT_MEDIA_UNAVAILABLE"
CONTENT_MEDIA_FAILED = "CONTENT_MEDIA_FAILED"
CONTENT_PLAN_INVALID = "CONTENT_PLAN_INVALID"
CONTENT_METRICS_INVALID = "CONTENT_METRICS_INVALID"
CONTENT_ANALYTICS_FAILED = "CONTENT_ANALYTICS_FAILED"
CONTENT_OPTIMIZATION_INSUFFICIENT_EVIDENCE = "CONTENT_OPTIMIZATION_INSUFFICIENT_EVIDENCE"
CONTENT_OPTIMIZATION_FAILED = "CONTENT_OPTIMIZATION_FAILED"
CONTENT_BATCH_REQUIRED = "CONTENT_BATCH_REQUIRED"
CONTENT_CANCELLED = "CONTENT_CANCELLED"
CONTENT_DEADLINE_EXCEEDED = "CONTENT_DEADLINE_EXCEEDED"


class ContentBatchRequired(ContentIntelError):
    def __init__(self):
        super().__init__(CONTENT_BATCH_REQUIRED)


class ContentInsufficientEvidence(ContentIntelError):
    def __init__(self, detail: str = ""):
        super().__init__(CONTENT_OPTIMIZATION_INSUFFICIENT_EVIDENCE, detail)
