"""Controlled launch in-memory store protocol."""

from __future__ import annotations

from typing import Protocol

from controlled_launch.models import LaunchCandidate, LaunchEvidence, RolloutState, TrafficPolicy


class ControlledLaunchStore(Protocol):
    def save_candidate(self, candidate: LaunchCandidate) -> LaunchCandidate: ...
    def get_candidate(self, candidate_id: str) -> LaunchCandidate | None: ...
    def save_policy(self, policy: TrafficPolicy) -> TrafficPolicy: ...
    def get_policy(self, policy_id: str) -> TrafficPolicy | None: ...
    def latest_policy_for_candidate(self, candidate_id: str) -> TrafficPolicy | None: ...
    def save_rollout(self, state: RolloutState) -> RolloutState: ...
    def get_rollout(self, candidate_id: str) -> RolloutState | None: ...
    def save_evidence(self, evidence: LaunchEvidence) -> LaunchEvidence: ...
    def list_evidence(self, candidate_id: str) -> list[LaunchEvidence]: ...
    def append_audit(self, event: dict) -> dict: ...
    def list_audit(self, *, candidate_id: str | None = None) -> list[dict]: ...
