"""Integration family / adapter-type tokens for Tool Platform descriptors."""

from __future__ import annotations

# Canonical adapter family tokens (extensible; not an exhaustive enum lock-in)
ADAPTER_WEB_SEARCH = "WEB_SEARCH"
ADAPTER_BROWSER = "BROWSER"
ADAPTER_FILES = "FILES"
ADAPTER_TABULAR = "TABULAR"
ADAPTER_DOCUMENT = "DOCUMENT"
ADAPTER_EMAIL = "EMAIL"
ADAPTER_CALENDAR = "CALENDAR"
ADAPTER_MESSAGING = "MESSAGING"
ADAPTER_CRM = "CRM"
ADAPTER_CMS = "CMS"
ADAPTER_ERP = "ERP"
ADAPTER_DATABASE = "DATABASE"
ADAPTER_IMAGE = "IMAGE"
ADAPTER_SEO_ANALYTICS = "SEO_ANALYTICS"
ADAPTER_CRAWLER = "CRAWLER"
ADAPTER_MARKETPLACE = "MARKETPLACE"
ADAPTER_MCP = "MCP"
ADAPTER_GENERIC_HTTP = "GENERIC_HTTP"

INTEGRATION_FAMILIES = (
    ADAPTER_WEB_SEARCH,
    ADAPTER_BROWSER,
    ADAPTER_FILES,
    ADAPTER_TABULAR,
    ADAPTER_DOCUMENT,
    ADAPTER_EMAIL,
    ADAPTER_CALENDAR,
    ADAPTER_MESSAGING,
    ADAPTER_CRM,
    ADAPTER_CMS,
    ADAPTER_ERP,
    ADAPTER_DATABASE,
    ADAPTER_IMAGE,
    ADAPTER_SEO_ANALYTICS,
    ADAPTER_CRAWLER,
    ADAPTER_MARKETPLACE,
    ADAPTER_MCP,
    ADAPTER_GENERIC_HTTP,
)
